from typing import Optional
from pydantic import BaseModel, Field


class LLMRequest(BaseModel):
    """Pydantic model representing a prompt request configuration for the LLM Provider."""

    prompt: str = Field(..., description="The user/system formatted prompt to send to the model.")
    model: str = Field(..., description="The target LLM model identifier.")
    temperature: float = Field(default=0.0, description="Sampling temperature to govern output variation.")


class LLMResponse(BaseModel):
    """Pydantic model representing a structured and normalized response from the LLM Provider."""

    content: str = Field(..., description="The textual answer generated by the LLM.")
    model: str = Field(..., description="The model name that produced this response.")
    latency_ms: float = Field(..., description="Execution time of the request in milliseconds.")
    prompt_tokens: Optional[int] = Field(default=None, description="Number of tokens within the input prompt.")
    completion_tokens: Optional[int] = Field(default=None, description="Number of tokens in the generated response.")
